name: quicki
version: 1.0.0+1
publish_to: none
description: A ride-hailing application for final year project.
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 4.0.0
  flutter_datetime_picker: 1.5.1
  flutter_polyline_points: 1.0.0
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.1.1
  geocoding: 2.0.1
  get: 4.3.8
  image_cropper: ^1.4.0
  image_picker: ^0.7.5+3
  intl: 0.17.0
  location: 4.3.0
  lottie: ^1.2.1
  path_provider: ^2.0.2
  url_launcher: 6.0.12
  permission_handler: ^8.1.6
  shared_preferences: ^2.0.11
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/ad1.png
    - assets/images/ad2.png
    - assets/images/ad3.png
    - assets/images/pin.png
    - assets/animations/car_animation1.json
    - assets/animations/splash.json
    - assets/animations/login.json
    - assets/svg_images/
    - assets/images/motorcycle.png
    - assets/svg_images/warning.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat/Montserrat-Light.ttf
        - asset: font/Montserrat/Montserrat-Thin.ttf
        - asset: font/Montserrat/Montserrat-Regular.ttf
        - asset: font/Montserrat/Montserrat-Medium.ttf
        - asset: font/Montserrat/Montserrat-SemiBold.ttf
        - asset: font/Montserrat/Montserrat-Bold.ttf
          weight: 500
