name: quicki
version: 1.0.0+1
publish_to: none
description: A ride-hailing application for final year project.
environment: 
  sdk: '>=2.15.0-233.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat/Montserrat-Light.ttf
        - asset: font/Montserrat/Montserrat-Thin.ttf
        - asset: font/Montserrat/Montserrat-Regular.ttf
        - asset: font/Montserrat/Montserrat-Medium.ttf
        - asset: font/Montserrat/Montserrat-SemiBold.ttf
        - asset: font/Montserrat/Montserrat-Bold.ttf
          weight: 500
